export default {
  button: 'Select Date for Available Bikes',
  model: 'Model',
  color: 'Color',
  location: 'Location',
  rating: 'Rating',
  bike: '. Bike',
  filters: 'Filters',
  selected_date: 'Selected Date',
  available_bikes: 'Available Bikes',
  not_applicable: 'N/A',
  fully_available: 'Fully available',
  sign_up: 'Sign Up',
  name: 'NAME',
  date_button: 'Select Date to Rent the Bike',
  rent: 'Rent',
  cancel_rent: 'Cancel Rent',
  rate_bike: 'Rate Bike',
  calendar_days_abbreviations: {
    Sunday: 'Sun',
    Monday: 'Mon',
    Tuesday: 'Tue',
    Wednesday: 'Wed',
    Thursday: 'Thu',
    Friday: 'Fri',
    Saturday: 'Sat',
  },
  calendar_months: {
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
  },
  week_days: {
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
  },
  date_header: 'Date',
  password: 'Password',
  or: 'or',
  login: 'Login',
  email_address: 'Email Address',
  dont_have_account: "Don't have an account? ",
  already_have_account: 'Already have an account? ',
  all_fields_are_required: 'All fields are required',
};
